seed: 42

storage:
  video_root: "Data/video"
  frames_root: "Data/frames"
  metadata_json: "Data/metadata.json"
  embeddings_folder_per_movie: "Data/embeddings"
  face_crops_root: "Data/face_crops"

  warehouse_embeddings: "warehouse/parquet/embeddings.parquet"
  warehouse_embeddings_pca: "warehouse/parquet/embeddings_pca.parquet"
  warehouse_clusters: "warehouse/parquet/clusters.parquet"
  warehouse_noise: "warehouse/parquet/noise.parquet"
  clusters_merged_parquet: "warehouse/parquet/clusters_merged.parquet"
  cluster_previews_root: "warehouse/cluster_previews"

  characters_json: "warehouse/characters.json"
  pca_model: "models/pca_model.joblib"
  index_path: "models/character_index.faiss"
  index_map: "models/character_index_map.json"

embedding:
  model: "buffalo_l"
  l2_normalize: true
  providers: ["CUDAExecutionProvider"]

pca:
  enable: true
  n_components: 256
  whiten: false

clustering:
  algo: "agglomerative"        # tạm bỏ auto/HDBSCAN cho ổn định
  metric: "euclidean"          # tránh fallback khó kiểm soát
  linkage: "complete"
  auto_distance_percentile: 95
  distance_threshold:
    default: 0.43              # cho 256-D PCA + L2
  distance_threshold_pca: 0.9
  hdbscan:
    use_precomputed: true
    min_cluster_size: 5
    min_samples: 5

merge:
  global_threshold: 0.78       # cosine similarity threshold for global merge

post_merge:
  enable: true
  metric: "euclidean"          # thống nhất với trên
  linkage: "average"
  distance_threshold: 0.55     # NGUYÊN NHÂN CHÍNH khiến còn 2–4 người

filter:
  min_track_size: 5
  min_cluster_size: 3

filter_clusters:
  min_size: 6
#  min_det: 0.6
#  min_frames: 5

quality_filters:
  enable: true
  min_det_score: 0.4
  min_face_ratio: 0.003
  min_blur_clarity: 60.0
  brightness:
    enable: true
    value_range: [30, 230]
  contrast:
    enable: true
    min_value: 25.0

centroid:
  method: "trimmed_mean"
  trim_ratio: 0.20

index:
  type: "flat_ip"

  search:
    knn: 1
    noise_knn: 50
    noise_cosine_floor: 0.45
    sim_threshold: 0.5
    margin_threshold: 0.05
    ratio_threshold: 1.1
    min_count: 3

logging:
  mlflow_experiment: "face_discovery_mvp"

search:
  threshold: 0.45
  top_k: 5
